// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rramesh/eatables/sdk/models"
)

// CreateItemReader is a Reader for the CreateItem structure.
type CreateItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCreateItemUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewCreateItemNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateItemOK creates a CreateItemOK with default headers values
func NewCreateItemOK() *CreateItemOK {
	return &CreateItemOK{}
}

/*CreateItemOK handles this case with default header values.

A list of eatable items returned in the response
*/
type CreateItemOK struct {
	Payload []*models.Item
}

func (o *CreateItemOK) Error() string {
	return fmt.Sprintf("[POST /items][%d] createItemOK  %+v", 200, o.Payload)
}

func (o *CreateItemOK) GetPayload() []*models.Item {
	return o.Payload
}

func (o *CreateItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateItemUnprocessableEntity creates a CreateItemUnprocessableEntity with default headers values
func NewCreateItemUnprocessableEntity() *CreateItemUnprocessableEntity {
	return &CreateItemUnprocessableEntity{}
}

/*CreateItemUnprocessableEntity handles this case with default header values.

Validation errors defined as an array of strings
*/
type CreateItemUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *CreateItemUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /items][%d] createItemUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateItemUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *CreateItemUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateItemNotImplemented creates a CreateItemNotImplemented with default headers values
func NewCreateItemNotImplemented() *CreateItemNotImplemented {
	return &CreateItemNotImplemented{}
}

/*CreateItemNotImplemented handles this case with default header values.

Generic error message returned as a string
*/
type CreateItemNotImplemented struct {
	Payload *models.GenericError
}

func (o *CreateItemNotImplemented) Error() string {
	return fmt.Sprintf("[POST /items][%d] createItemNotImplemented  %+v", 501, o.Payload)
}

func (o *CreateItemNotImplemented) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CreateItemNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
