// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rramesh/eatables/sdk/models"
)

// DeleteItemReader is a Reader for the DeleteItem structure.
type DeleteItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteItemCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteItemNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewDeleteItemNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteItemCreated creates a DeleteItemCreated with default headers values
func NewDeleteItemCreated() *DeleteItemCreated {
	return &DeleteItemCreated{}
}

/*DeleteItemCreated handles this case with default header values.

No content is returned by this API endpoint
*/
type DeleteItemCreated struct {
}

func (o *DeleteItemCreated) Error() string {
	return fmt.Sprintf("[DELETE /items/{id}][%d] deleteItemCreated ", 201)
}

func (o *DeleteItemCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteItemNotFound creates a DeleteItemNotFound with default headers values
func NewDeleteItemNotFound() *DeleteItemNotFound {
	return &DeleteItemNotFound{}
}

/*DeleteItemNotFound handles this case with default header values.

Generic error message returned as a string
*/
type DeleteItemNotFound struct {
	Payload *models.GenericError
}

func (o *DeleteItemNotFound) Error() string {
	return fmt.Sprintf("[DELETE /items/{id}][%d] deleteItemNotFound  %+v", 404, o.Payload)
}

func (o *DeleteItemNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteItemNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteItemNotImplemented creates a DeleteItemNotImplemented with default headers values
func NewDeleteItemNotImplemented() *DeleteItemNotImplemented {
	return &DeleteItemNotImplemented{}
}

/*DeleteItemNotImplemented handles this case with default header values.

Generic error message returned as a string
*/
type DeleteItemNotImplemented struct {
	Payload *models.GenericError
}

func (o *DeleteItemNotImplemented) Error() string {
	return fmt.Sprintf("[DELETE /items/{id}][%d] deleteItemNotImplemented  %+v", 501, o.Payload)
}

func (o *DeleteItemNotImplemented) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteItemNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
