// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListItemsByVendorParams creates a new ListItemsByVendorParams object
// with the default values initialized.
func NewListItemsByVendorParams() *ListItemsByVendorParams {
	var ()
	return &ListItemsByVendorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListItemsByVendorParamsWithTimeout creates a new ListItemsByVendorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListItemsByVendorParamsWithTimeout(timeout time.Duration) *ListItemsByVendorParams {
	var ()
	return &ListItemsByVendorParams{

		timeout: timeout,
	}
}

// NewListItemsByVendorParamsWithContext creates a new ListItemsByVendorParams object
// with the default values initialized, and the ability to set a context for a request
func NewListItemsByVendorParamsWithContext(ctx context.Context) *ListItemsByVendorParams {
	var ()
	return &ListItemsByVendorParams{

		Context: ctx,
	}
}

// NewListItemsByVendorParamsWithHTTPClient creates a new ListItemsByVendorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListItemsByVendorParamsWithHTTPClient(client *http.Client) *ListItemsByVendorParams {
	var ()
	return &ListItemsByVendorParams{
		HTTPClient: client,
	}
}

/*ListItemsByVendorParams contains all the parameters to send to the API endpoint
for the list items by vendor operation typically these are written to a http.Request
*/
type ListItemsByVendorParams struct {

	/*UUID
	  The UUID of the item for which the operation relates

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list items by vendor params
func (o *ListItemsByVendorParams) WithTimeout(timeout time.Duration) *ListItemsByVendorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list items by vendor params
func (o *ListItemsByVendorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list items by vendor params
func (o *ListItemsByVendorParams) WithContext(ctx context.Context) *ListItemsByVendorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list items by vendor params
func (o *ListItemsByVendorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list items by vendor params
func (o *ListItemsByVendorParams) WithHTTPClient(client *http.Client) *ListItemsByVendorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list items by vendor params
func (o *ListItemsByVendorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the list items by vendor params
func (o *ListItemsByVendorParams) WithUUID(uuid string) *ListItemsByVendorParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the list items by vendor params
func (o *ListItemsByVendorParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *ListItemsByVendorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
