// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListSingleItemParams creates a new ListSingleItemParams object
// with the default values initialized.
func NewListSingleItemParams() *ListSingleItemParams {
	var ()
	return &ListSingleItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListSingleItemParamsWithTimeout creates a new ListSingleItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSingleItemParamsWithTimeout(timeout time.Duration) *ListSingleItemParams {
	var ()
	return &ListSingleItemParams{

		timeout: timeout,
	}
}

// NewListSingleItemParamsWithContext creates a new ListSingleItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSingleItemParamsWithContext(ctx context.Context) *ListSingleItemParams {
	var ()
	return &ListSingleItemParams{

		Context: ctx,
	}
}

// NewListSingleItemParamsWithHTTPClient creates a new ListSingleItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListSingleItemParamsWithHTTPClient(client *http.Client) *ListSingleItemParams {
	var ()
	return &ListSingleItemParams{
		HTTPClient: client,
	}
}

/*ListSingleItemParams contains all the parameters to send to the API endpoint
for the list single item operation typically these are written to a http.Request
*/
type ListSingleItemParams struct {

	/*ID
	  The id of the item for which the operation relates

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list single item params
func (o *ListSingleItemParams) WithTimeout(timeout time.Duration) *ListSingleItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list single item params
func (o *ListSingleItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list single item params
func (o *ListSingleItemParams) WithContext(ctx context.Context) *ListSingleItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list single item params
func (o *ListSingleItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list single item params
func (o *ListSingleItemParams) WithHTTPClient(client *http.Client) *ListSingleItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list single item params
func (o *ListSingleItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list single item params
func (o *ListSingleItemParams) WithID(id int64) *ListSingleItemParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list single item params
func (o *ListSingleItemParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListSingleItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
