// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rramesh/eatables/sdk/models"
)

// UpdateItemReader is a Reader for the UpdateItem structure.
type UpdateItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateItemCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUpdateItemNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateItemUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateItemCreated creates a UpdateItemCreated with default headers values
func NewUpdateItemCreated() *UpdateItemCreated {
	return &UpdateItemCreated{}
}

/*UpdateItemCreated handles this case with default header values.

No content is returned by this API endpoint
*/
type UpdateItemCreated struct {
}

func (o *UpdateItemCreated) Error() string {
	return fmt.Sprintf("[PUT /items][%d] updateItemCreated ", 201)
}

func (o *UpdateItemCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateItemNotFound creates a UpdateItemNotFound with default headers values
func NewUpdateItemNotFound() *UpdateItemNotFound {
	return &UpdateItemNotFound{}
}

/*UpdateItemNotFound handles this case with default header values.

Generic error message returned as a string
*/
type UpdateItemNotFound struct {
	Payload *models.GenericError
}

func (o *UpdateItemNotFound) Error() string {
	return fmt.Sprintf("[PUT /items][%d] updateItemNotFound  %+v", 404, o.Payload)
}

func (o *UpdateItemNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateItemNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateItemUnprocessableEntity creates a UpdateItemUnprocessableEntity with default headers values
func NewUpdateItemUnprocessableEntity() *UpdateItemUnprocessableEntity {
	return &UpdateItemUnprocessableEntity{}
}

/*UpdateItemUnprocessableEntity handles this case with default header values.

Validation errors defined as an array of strings
*/
type UpdateItemUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *UpdateItemUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /items][%d] updateItemUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *UpdateItemUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *UpdateItemUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
